% Purpose: To create the figures for the COUGARxt POMA
clear; close all;

plotStyle('StandardStyle','SonicBoom')

path = '/Volumes/Mark Drive/Acoustics Research/Acoustics/Arc Measurements';
angles = [5,20,45,70,90];
savePath = '/Users/markanderson/Desktop/Mark_Anderson_Senior_Thesis_Document/Figures';
FileTypes = ["png"];

%% Comparing COUGAR without a windscreen to the baseline
session_baseline = 'Spring 2019';
configuration_baseline = 'Quarter Inch Baseline';
session_dut = 'Spring 2019';
configuration_dut = 'COUGAR No Wind Screen';
comparison = compareTwoConfigurations(path,...
                                      session_baseline,...
                                      configuration_baseline,...
                                      session_dut,...
                                      configuration_dut,...
                                      angles);
createPlot(comparison)
ylim([-3,3])

savePlots('SavePath',savePath,...
          'Titles',strcat(configuration_dut," - ",configuration_baseline),...
          'FileTypes',FileTypes)
      
%% Comparing COUGAR with a thin plate (no screen) to the baseline
session_baseline = 'Spring 2019';
configuration_baseline = 'Quarter Inch Baseline';
session_dut = 'Spring 2019';
configuration_dut = 'Thin COUGAR No Wind Screen';
comparison = compareTwoConfigurations(path,...
                                      session_baseline,...
                                      configuration_baseline,...
                                      session_dut,...
                                      configuration_dut,...
                                      angles);
createPlot(comparison)
ylim([-3,3])

savePlots('SavePath',savePath,...
          'Titles',strcat(configuration_dut," - ",configuration_baseline),...
          'FileTypes',FileTypes)
      
%% Comparing COUGAR with a centered apex (no screen) to the baseline
session_baseline = 'Spring 2019';
configuration_baseline = 'Quarter Inch Baseline';
session_dut = 'Spring 2019';
configuration_dut = 'Bulge In Center No Wind Screen';
comparison = compareTwoConfigurations(path,...
                                      session_baseline,...
                                      configuration_baseline,...
                                      session_dut,...
                                      configuration_dut,...
                                      angles);
createPlot(comparison)
ylim([-3,3])

savePlots('SavePath',savePath,...
          'Titles',strcat(configuration_dut," - ",configuration_baseline),...
          'FileTypes',FileTypes)
      
%% COUGAR windscreen insertion loss (negative)
session_baseline = 'Spring 2019';
configuration_baseline = 'COUGAR No Wind Screen';
session_dut = 'Spring 2019';
configuration_dut = 'COUGAR With Wind Screen No Rain Cap';
comparison = compareTwoConfigurations(path,...
                                      session_baseline,...
                                      configuration_baseline,...
                                      session_dut,...
                                      configuration_dut,...
                                      angles);
createPlot(comparison)
ylim([-3,3])

savePlots('SavePath',savePath,...
          'Titles',strcat(configuration_dut," - ",configuration_baseline),...
          'FileTypes',FileTypes)
      
%% Testing the Rain Cap
session_baseline = 'Spring 2019';
configuration_baseline = 'COUGAR With Wind Screen No Rain Cap';
session_dut = 'Spring 2019';
configuration_dut = 'COUGAR With Wind Screen';
comparison = compareTwoConfigurations(path,...
                                      session_baseline,...
                                      configuration_baseline,...
                                      session_dut,...
                                      configuration_dut,...
                                      angles);
createPlot(comparison)
ylim([-5,5])

savePlots('SavePath',savePath,...
          'Titles',strcat(configuration_dut," - ",configuration_baseline),...
          'FileTypes',FileTypes)
      
%% Testing with water saturation
session_baseline = 'Spring 2019';
configuration_baseline = 'COUGAR With Wind Screen';
session_dut = 'Spring 2019';
configuration_dut = 'COUGAR Water Saturated';
comparison = compareTwoConfigurations(path,...
                                      session_baseline,...
                                      configuration_baseline,...
                                      session_dut,...
                                      configuration_dut,...
                                      angles);
createPlot(comparison)
ylim([-5,5])

savePlots('SavePath',savePath,...
          'Titles',strcat(configuration_dut," - ",configuration_baseline),...
          'FileTypes',FileTypes)
      
%% Testing with dirt saturation
session_baseline = 'Spring 2019';
configuration_baseline = 'COUGAR With Pre Dirt Wind Screen';
session_dut = 'Spring 2019';
configuration_dut = 'COUGAR With Wind Screen Dirt Saturated Round 3';
comparison = compareTwoConfigurations(path,...
                                      session_baseline,...
                                      configuration_baseline,...
                                      session_dut,...
                                      configuration_dut,...
                                      angles);
createPlot(comparison)
ylim([-5,5])

savePlots('SavePath',savePath,...
          'Titles',strcat(configuration_dut," - ",configuration_baseline),...
          'FileTypes',FileTypes)
      
%% Final COUGAR design
session_baseline = 'Spring 2019';
configuration_baseline = 'Quarter Inch Baseline';
session_dut = 'Spring 2019';
configuration_dut = 'COUGAR With Wind Screen No Rain Cap';
comparison = compareTwoConfigurations(path,...
                                      session_baseline,...
                                      configuration_baseline,...
                                      session_dut,...
                                      configuration_dut,...
                                      angles);
createPlot(comparison)
ylim([-3,3])

savePlots('SavePath',savePath,...
          'Titles',strcat(configuration_dut," - ",configuration_baseline),...
          'FileTypes',FileTypes)
      
%% COUGAR Azimuthal Rotation at 5 Degrees Elevation
session = 'Fall 2019';
configuration = 'COUGAR 1.0';
elevationAngle = 5;
azimuthalAngles = [0,45,90,135,180,270];
comparison = performAzimuthalRotation(path,...
                                      session,...
                                      configuration,...
                                      elevationAngle,...
                                      azimuthalAngles);
createPlot(comparison)
ylim([-3,3])

savePlots('SavePath',savePath,...
          'Titles',strcat("COUGAR Azimuthal Rotation at ",num2str(elevationAngle)," Degrees"),...
          'FileTypes',FileTypes)
      
%% COUGAR Azimuthal Rotation at 45 Degrees Elevation
session = 'Fall 2019';
configuration = 'COUGAR 1.0';
elevationAngle = 45;
azimuthalAngles = [0,45,90,135,180,270];
comparison = performAzimuthalRotation(path,...
                                      session,...
                                      configuration,...
                                      elevationAngle,...
                                      azimuthalAngles);
createPlot(comparison)
ylim([-3,3])

savePlots('SavePath',savePath,...
          'Titles',strcat("COUGAR Azimuthal Rotation at ",num2str(elevationAngle)," Degrees"),...
          'FileTypes',FileTypes)
      
%% COUGAR Azimuthal Rotation at 90 Degrees Elevation
session = 'Fall 2019';
configuration = 'COUGAR 1.0';
elevationAngle = 90;
azimuthalAngles = [0,45,90,135,180,270];
comparison = performAzimuthalRotation(path,...
                                      session,...
                                      configuration,...
                                      elevationAngle,...
                                      azimuthalAngles);
createPlot(comparison)
ylim([-3,3])

savePlots('SavePath',savePath,...
          'Titles',strcat("COUGAR Azimuthal Rotation at ",num2str(elevationAngle)," Degrees"),...
          'FileTypes',FileTypes)

%% COUGARxt in Standard Configuration
session_baseline = 'Fall 2019';
configuration_baseline = 'BASELINE 2';
session_dut = 'Fall 2019';
configuration_dut = 'COUGAR 2.0 (0 Degrees Azimuth)';
comparison = compareTwoConfigurations(path,...
                                      session_baseline,...
                                      configuration_baseline,...
                                      session_dut,...
                                      configuration_dut,...
                                      angles);
createPlot(comparison)
ylim([-3,3])

savePlots('SavePath',savePath,...
          'Titles',strcat("COUGARxt (0 Degrees Azimuth) - ",configuration_baseline),...
          'FileTypes',FileTypes)
      
%% COUGARxt Rain Cap Test
session_baseline = 'Fall 2019';
configuration_baseline = 'COUGAR 2.0 (0 Degrees Azimuth)';
session_dut = 'Fall 2019';
configuration_dut = 'COUGAR 2.0 With Rain Cap (0 Degrees Azimuth)';
comparison = compareTwoConfigurations(path,...
                                      session_baseline,...
                                      configuration_baseline,...
                                      session_dut,...
                                      configuration_dut,...
                                      angles);
createPlot(comparison)
ylim([-8,5])

savePlots('SavePath',savePath,...
          'Titles',strcat("COUGARxt With Rain Cap (0 Degrees Azimuth) - COUGARxt (0 Degrees Azimuth)"),...
          'FileTypes',FileTypes)
      
%% COUGARxt Azimuthal Rotation at 5 Degrees Elevation
session = 'Fall 2019';
configuration = 'COUGAR 2.0';
elevationAngle = 5;
azimuthalAngles = [0,45,90,135,180,270];
comparison = performAzimuthalRotation(path,...
                                      session,...
                                      configuration,...
                                      elevationAngle,...
                                      azimuthalAngles);
createPlot(comparison)
ylim([-3,3])

savePlots('SavePath',savePath,...
          'Titles',strcat("COUGARxt Azimuthal Rotation at ",num2str(elevationAngle)," Degrees"),...
          'FileTypes',FileTypes)
      
%% COUGARxt Azimuthal Rotation at 45 Degrees Elevation
session = 'Fall 2019';
configuration = 'COUGAR 2.0';
elevationAngle = 45;
azimuthalAngles = [0,45,90,135,180,270];
comparison = performAzimuthalRotation(path,...
                                      session,...
                                      configuration,...
                                      elevationAngle,...
                                      azimuthalAngles);
createPlot(comparison)
ylim([-3,3])

savePlots('SavePath',savePath,...
          'Titles',strcat("COUGARxt Azimuthal Rotation at ",num2str(elevationAngle)," Degrees"),...
          'FileTypes',FileTypes)
      
%% COUGARxt Azimuthal Rotation at 90 Degrees Elevation
session = 'Fall 2019';
configuration = 'COUGAR 2.0';
elevationAngle = 90;
azimuthalAngles = [0,45,90,135,180,270];
comparison = performAzimuthalRotation(path,...
                                      session,...
                                      configuration,...
                                      elevationAngle,...
                                      azimuthalAngles);
createPlot(comparison)
ylim([-3,3])

savePlots('SavePath',savePath,...
          'Titles',strcat("COUGARxt Azimuthal Rotation at ",num2str(elevationAngle)," Degrees"),...
          'FileTypes',FileTypes)
      
%% COUGAR vs COUGARxt Lab Test
session_baseline = 'Summer 2020';
configuration_baseline = 'COUGAR With Windscreen';
session_dut = 'Summer 2020';
configuration_dut = 'COUGARxt With Windscreen';
comparison = compareTwoConfigurations(path,...
                                      session_baseline,...
                                      configuration_baseline,...
                                      session_dut,...
                                      configuration_dut,...
                                      angles);
createPlot(comparison)
ylim([-3,3])

savePlots('SavePath',savePath,...
          'Titles',strcat(configuration_dut," - ",configuration_baseline),...
          'FileTypes',FileTypes)
      
%% Wind Noise Comparison

disp('Starting Wind Noise Comparison, this will take a few minutes...')
Wind_Noise_Comparison

savePlots('SavePath',savePath,...
          'Titles',"Wind Noise Comparison",...
          'FileTypes',FileTypes)

function createPlot(comparison)

    % Formatting the plot
    comparison.compareSpectra('SpectrumType','OTO',...
                              'LineWidth',2);
    xlim([50,20e3])
    ylim([-5,5])
    xlabel('Frequency (Hz)')
    ylabel('Difference (dB)')
    
    % Formatting the legend
    ax = gca;
    hleg = legend(ax.Children(2:end));
    hleg.Title.String = 'Elevation Angle';
    hleg.Title.FontWeight = 'Bold';
    hleg.Location = 'NorthWest';
    
    title('')
    
    legend('Autoupdate','off')
    l = yline(0,'k--','LineWidth',4);
    uistack(l,'bottom') % Putting the reference line underneath the data

end